/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tomaszrarok;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonSyntaxException;
import com.tomaszrarok.danewejsciowe.DaneWejsciowe;
import com.tomaszrarok.danewejsciowe.Pracownik;
import com.tomaszrarok.danewejsciowe.Projekt;
import com.tomaszrarok.danewejsciowe.Zadanie;
import com.tomaszrarok.decyzja.Decyzja;
import com.tomaszrarok.decyzja.ZbiorMozliwychDecyzji;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomasz Rarok
 */
public class GlowneOkno extends javax.swing.JFrame {

    /**
     * Creates new form GlowneOkno
     */
    public GlowneOkno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zarzadzanie Projektami");

        jButton1.setText("wczytaj z pliku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Dane Wejsciowe");

        jLabel2.setText("Wyniki");
        jLabel2.setToolTipText("");

        jScrollPane2.setViewportView(jList1);

        jButton3.setText("start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 695, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int returnVal = jFileChooser1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooser1.getSelectedFile();
            try {               
                jTextArea1.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //PROJEKT
        Projekt projekt = new Projekt();
        Zadanie zadanie1 = new Zadanie(5.0);
        Zadanie zadanie2 = new Zadanie(7.0);
        Zadanie zadanie3 = new Zadanie(10.0);
        Zadanie zadanie4 = new Zadanie(4.0);
        Zadanie zadanie5 = new Zadanie(6.0);
        Zadanie zadanie6 = new Zadanie(20.0);
        Zadanie zadanie7 = new Zadanie(4.0);
        
        Map<String, Double> priorytety = new HashMap<String, Double>();
        priorytety.put("czas", 1.2);
        priorytety.put("koszt", 1.2);
        priorytety.put("umiejetnosc", 1.2);

        List zadania = new ArrayList( Arrays.asList(zadanie1, zadanie2, zadanie3, zadanie4, zadanie5, zadanie6, zadanie7));
        
        projekt.setZadania(zadania);
        projekt.setWymagania(new ArrayList<>(Arrays.asList(new String[]{"umiejetnosc1", "umiejetnosc2", "umiejetnosc3", "umiejetnosc4", "umiejetnosc5", "umiejetnosc6"})));

       //PRACOWNIK 1
        Pracownik pracownik1 = new Pracownik("p1");
        pracownik1.setKosztGodzinyPracy(20.0);
        pracownik1.setProcentowyKosztDouczenia(70.0);
        pracownik1.setUmiejetnosci(new ArrayList<>(Arrays.asList(new String[]{"umiejetnosc1", "umiejetnosc2","umiejetnosc4", "umiejetnosc5"})));

        //PRACOWNIK 2
        Pracownik pracownik2 = new Pracownik("p2");
        pracownik2.setKosztGodzinyPracy(22.0);
        pracownik2.setProcentowyKosztDouczenia(60.0);
        pracownik2.setUmiejetnosci(new ArrayList<>(Arrays.asList(new String[]{"umiejetnosc1", "umiejetnosc2", "umiejetnosc3", "umiejetnosc4"})));

        //PRACOWNIK 3
        Pracownik pracownik3 = new Pracownik("p3");
        pracownik3.setKosztGodzinyPracy(15.0);
        pracownik3.setProcentowyKosztDouczenia(120.0);
        pracownik3.setUmiejetnosci(new ArrayList<>(Arrays.asList(new String[]{"umiejetnosc1", "umiejetnosc2", "umiejetnosc3"})));

        //PRACOWNIK 4
        Pracownik pracownik4 = new Pracownik("p4");
        pracownik4.setKosztGodzinyPracy(25.0);
        pracownik4.setProcentowyKosztDouczenia(20.0);
        pracownik4.setUmiejetnosci(new ArrayList<String>(Arrays.asList(new String[]{"umiejetnosc1", "umiejetnosc2"})));
        
        DaneWejsciowe daneWejsciowe;
        daneWejsciowe = new DaneWejsciowe(priorytety, projekt, Arrays.asList(pracownik1, pracownik2, pracownik3, pracownik4));
        
         Gson gson = new GsonBuilder().setPrettyPrinting().create();
         
         jTextArea1.setText(gson.toJson(daneWejsciowe));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        Gson gson = new Gson();
        
        DaneWejsciowe dw = null;
        try{
            dw = gson.fromJson(jTextArea1.getText(), DaneWejsciowe.class); 
        } catch(JsonSyntaxException ex){
            
        }
             
        if(dw == null ){
            showAlert("Nie moglem przeczytac danych wejsciowych!");
            return;
        }        
        
        String validation = dw.validation();
        if( validation != null){
            showAlert(validation);
            return;
        }
        HashMap<Integer, Pracownik> mapaPracownikow = new HashMap<>();
        int i = 1;
        for(Pracownik p : dw.getPracownicy()){
            mapaPracownikow.put(i, p);
            i++;
        }
        ZbiorMozliwychDecyzji zmd = new ZbiorMozliwychDecyzji(dw.getProjekt(), mapaPracownikow, dw.getPriorytety());
        
        List<Decyzja> decyzje = zmd.pobierzWedlugNajlepszej();
        
        DefaultListModel listModel = new DefaultListModel();
        if( decyzje.size() > 10 ){
            decyzje = decyzje.subList(0, 10);
        }
        listModel.addElement("Niepreferencyjna");
        for(Decyzja item : decyzje){
            listModel.addElement(item.toString());
        }
        
        decyzje = zmd.pobierzWedlugApriori();
        if( decyzje.size() > 10 ){
            decyzje = decyzje.subList(0, 10);
        }
        listModel.addElement("Preferencyjna Apriori - metoda ograniczonych kryteriow");        
        for(Decyzja item : decyzje){
            listModel.addElement(item.toString());
        }
        
        jList1.setModel(listModel);
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlowneOkno.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlowneOkno.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlowneOkno.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlowneOkno.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlowneOkno().setVisible(true);
            }
        });
    }
    
    private void showAlert(String message){
        JOptionPane.showMessageDialog(null, message, "Alert", JOptionPane.ERROR_MESSAGE); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
